#!/bin/sh

if (rauc status | grep -q 'Booted from: rootfs.0 (system0)' &&
   rauc status | grep -q 'Activated: rootfs.1 (system1)') ||
   (rauc status | grep -q 'Booted from: rootfs.1 (system1)' &&
   rauc status | grep -q 'Activated: rootfs.0 (system0)'); then
    echo 0 > /sys/class/leds/led-green/brightness
    echo 0 > /sys/class/leds/led-blue/brightness
    echo heartbeat > /sys/class/leds/led-red/trigger

elif rauc status | grep -q 'Booted from: rootfs.1 (system1)' &&
     rauc status | grep -q 'Activated: rootfs.1 (system1)'; then
    echo 0 > /sys/class/leds/led-green/brightness
    echo 0 > /sys/class/leds/led-red/brightness
    echo heartbeat > /sys/class/leds/led-blue/trigger

elif rauc status | grep -q 'Booted from: rootfs.0 (system0)' &&
     rauc status | grep -q 'Activated: rootfs.0 (system0)'; then
    echo 0 > /sys/class/leds/led-blue/brightness
    echo 0 > /sys/class/leds/led-red/brightness
    echo heartbeat > /sys/class/leds/led-green/trigger
fi
