#!/bin/sh

RAUC_STATUS=$(rauc status)
BOOTED_SLOT=$(printf "$RAUC_STATUS" | grep -Eo "(Booted from: [[:alpha:]]+.)[01]" | grep -Eo "[01]$")
ACTIVATED_SLOT=$(printf "$RAUC_STATUS" | grep -Eo "(Activated: [[:alpha:]]+.)[01]" | grep -Eo "[01]$")

if [ \( "$BOOTED_SLOT" = 0 -a "$ACTIVATED_SLOT" = 1 \) -o \( "$BOOTED_SLOT" = 1 -a "$ACTIVATED_SLOT" = 0 \) ]; then
    printf 0 > /sys/class/leds/green\:cpu/brightness
    printf 0 > /sys/class/leds/blue\:disk/brightness
    printf heartbeat > /sys/class/leds/red\:disk/trigger
elif [ "$BOOTED_SLOT" = 0 ]; then
    printf 0 > /sys/class/leds/blue\:disk/brightness
    printf 0 > /sys/class/leds/red\:disk/brightness
    printf heartbeat > /sys/class/leds/green\:cpu/trigger
elif [ "$BOOTED_SLOT" = 1 ]; then
    printf 0 > /sys/class/leds/green\:cpu/brightness
    printf 0 > /sys/class/leds/red\:disk/brightness
    printf heartbeat > /sys/class/leds/blue\:disk/trigger
fi
